# Generated by Django 3.2 on 2021-05-03 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.DurationField(blank=True, help_text='Tiempo de duración de la pelicula', verbose_name='Duración')),
                ('director', models.ForeignKey(blank=True, help_text='Director de la Pelicula', null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.persona', verbose_name='Director')),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada_nro', models.PositiveIntegerField(blank=True, help_text='Numero de la temporada', verbose_name='Temporada Numero')),
                ('temporada_duracion', models.DurationField(blank=True, help_text='Tiempo de duracion de la temporada completa', verbose_name='Duración')),
                ('cant_cap', models.PositiveIntegerField(blank=True, help_text='Cantidad de capitulos de la temporada', verbose_name='Cantidad de capitulos')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pelicula', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pelicula')),
                ('id_serie', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula_Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la pelicula / serie', max_length=50, verbose_name='Nombre')),
                ('año', models.PositiveIntegerField(blank=True, help_text='Año en que se publico el libro.', null=True, verbose_name='Año de publicación')),
                ('puntaje_imdb', models.DecimalField(blank=True, decimal_places=1, help_text='Puntaje de la pagina IMDb', max_digits=2, null=True, verbose_name='Puntaje IMDb')),
                ('genero', models.CharField(blank=True, help_text='Genero de la pelicula o serie', max_length=25, null=True, verbose_name='Genero')),
                ('img_portada', models.ImageField(blank=True, help_text='Imagen de portada de la pelicula o serie', null=True, upload_to='portada_img', verbose_name='Portada')),
                ('casting', models.OneToOneField(help_text='Casting de la pelicula o serie', on_delete=django.db.models.deletion.CASCADE, to='personas.casting', verbose_name='Casting')),
                ('pelicula_serie', models.ForeignKey(help_text='Es una pelicula o una serie?', on_delete=django.db.models.deletion.CASCADE, to='app.tipo', verbose_name='Pelicula / Serie')),
            ],
            options={
                'verbose_name': 'Pelicula o Serie',
                'verbose_name_plural': 'Peliculas o Series',
            },
        ),
    ]
