# Generated by Django 3.2 on 2021-05-19 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210516_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula_serie',
            name='año',
            field=models.PositiveIntegerField(blank=True, help_text='Año en que se estreno la pelicula/serie.', null=True, verbose_name='Año de publicación'),
        ),
        migrations.AlterField(
            model_name='pelicula_serie',
            name='id_imdb',
            field=models.CharField(blank=True, help_text='ID unico de IMDb', max_length=25, null=True, verbose_name='ID IMDb'),
        ),
        migrations.AlterField(
            model_name='pelicula_serie',
            name='pelicula_serie',
            field=models.ForeignKey(help_text='ID', on_delete=django.db.models.deletion.CASCADE, to='app.tipo', verbose_name='Pelicula / Serie'),
        ),
    ]
