# Generated by Django 3.2 on 2021-05-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_auto_20210520_0004'),
        ('app', '0012_alter_pelicula_serie_img_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='director',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.ManyToManyField(blank=True, help_text='Director de la Pelicula', to='personas.Persona', verbose_name='Director'),
        ),
    ]
