# Generated by Django 3.2 on 2021-05-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_serie_temporada_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='cant_cap',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad de capitulos de la temporada', null=True, verbose_name='Cantidad de capitulos'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='temporada_duracion',
            field=models.IntegerField(blank=True, help_text='Tiempo de duracion de la temporada completa', null=True, verbose_name='Duración'),
        ),
    ]
