version: "3.8"
   
services:
  django: &django
    build:
      context: .
    container_name: django
    image: peliculas_series_django
    command: python manage.py runserver 0.0.0.0:8000
    hostname: django
    depends_on:
      - postgres
    volumes:
      - django-volume:/code
    ports:
      - "8000:8000"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    <<: *django
    container_name: celery
    image: peliculas_series_django
    command: bash -c "celery -A peliculas_series worker -l info"
    depends_on:
      - rabbitmq
      - django
    restart: on-failure
    ports: []

  flower:
    container_name: flower
    image: mher/flower:0.9.7
    environment:
      - CELERY_BROKER_URL=pyamqp://rabbitmq:5672
      - FLOWER_PORT=5555
    depends_on:
      - celery
      - rabbitmq
    ports:
      - "5555:5555" 
    
  postgres:
    container_name: postgres
    image: postgres:12.7
    hostname: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
  django-volume: