version: "3.8"
   
services:
  django:
    build: .
    container_name: django
    image: peliculas_series_django
    command: python manage.py runserver 0.0.0.0:8000
    hostname: django
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - main

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - main

  celery:
    container_name: celery
    image: peliculas_series_django
    command: bash -c "celery -A peliculas_series worker -l info"
    depends_on:
      - rabbitmq
      - django
    hostname: celery
    restart: on-failure
    networks:
      - main

  flower:
    container_name: flower
    image: mher/flower:0.9.7
    hostname: flower
    environment:
      - CELERY_BROKER_URL=pyamqp://rabbitmq:5672
      - FLOWER_PORT=5555
    depends_on:
      - celery
      - rabbitmq
    ports:
      - "5555:5555" 
    networks:
      - main

networks:
  main: