# Generated by Django 3.2 on 2021-05-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula_serie',
            name='id_imdb',
            field=models.CharField(blank=True, help_text='ID unico de IMDb', max_length=25, null=True, verbose_name='Id IMDb'),
        ),
    ]
