# Generated by Django 3.2 on 2021-05-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pelicula_serie_id_imdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.CharField(blank=True, help_text='Tiempo de duración de la pelicula', max_length=50, verbose_name='Duración'),
        ),
    ]
