# Generated by Django 3.2 on 2021-05-14 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_casting_options'),
        ('app', '0003_alter_pelicula_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula_serie',
            name='casting',
            field=models.OneToOneField(blank=True, help_text='Casting de la pelicula o serie', null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.casting', verbose_name='Casting'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='id_pelicula',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pelicula'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='id_serie',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.serie'),
        ),
    ]
