# Generated by Django 3.2 on 2021-05-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210514_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_genero', models.CharField(blank=True, help_text='Genero de la pelicula o serie', max_length=25, null=True, verbose_name='Genero')),
            ],
        ),
    ]
