# Generated by Django 3.2 on 2021-05-15 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_casting_options'),
        ('app', '0006_rename_generos_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula_serie',
            name='casting',
            field=models.OneToOneField(blank=True, default='', help_text='Casting de la pelicula o serie', on_delete=django.db.models.deletion.CASCADE, to='personas.casting', verbose_name='Casting'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pelicula_serie',
            name='genero',
        ),
        migrations.AddField(
            model_name='pelicula_serie',
            name='genero',
            field=models.ManyToManyField(blank=True, help_text='Genero de la pelicula o serie', null=True, to='app.Genero', verbose_name='Genero'),
        ),
    ]
