# Generated by Django 3.2 on 2021-05-15 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_casting_options'),
        ('app', '0007_auto_20210514_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula_serie',
            name='casting',
            field=models.OneToOneField(blank=True, help_text='Casting de la pelicula o serie', null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.casting', verbose_name='Casting'),
        ),
        migrations.AlterField(
            model_name='pelicula_serie',
            name='genero',
            field=models.ManyToManyField(blank=True, help_text='Genero de la pelicula o serie', to='app.Genero', verbose_name='Genero'),
        ),
    ]
