# Generated by Django 3.2 on 2021-05-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210514_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterField(
            model_name='genero',
            name='tipo_genero',
            field=models.CharField(blank=True, help_text='Genero de la pelicula o serie', max_length=50, null=True, unique=True, verbose_name='Genero'),
        ),
    ]
