# Generated by Django 3.2 on 2021-05-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_casting_options'),
        ('app', '0009_auto_20210514_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula_serie',
            name='casting',
        ),
        migrations.AddField(
            model_name='pelicula_serie',
            name='casting',
            field=models.ManyToManyField(blank=True, help_text='Casting de la pelicula o serie', to='personas.Persona', verbose_name='Casting'),
        ),
    ]
