# Generated by Django 3.2 on 2021-05-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210518_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula_serie',
            name='img_portada',
            field=models.CharField(blank=True, help_text='Imagen de portada de la pelicula o serie', max_length=300, null=True, verbose_name='Portada'),
        ),
    ]
