# Generated by Django 3.2 on 2021-05-22 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210520_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula_serie',
            name='pelicula_serie',
            field=models.ForeignKey(blank=True, help_text='ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tipo', verbose_name='Pelicula / Serie'),
        ),
    ]
