# Generated by Django 3.2 on 2021-05-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_pelicula_serie_pelicula_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='temporada_duracion',
            field=models.CharField(blank=True, help_text='Tiempo de duracion de la temporada completa', max_length=50, verbose_name='Duración'),
        ),
    ]
