# Generated by Django 3.2 on 2021-05-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_serie_temporada_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='temporada_duracion',
            field=models.IntegerField(blank=True, help_text='Tiempo de duracion de la temporada completa', max_length=50, verbose_name='Duración'),
        ),
    ]
