# Generated by Django 3.2 on 2021-05-02 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la persona', max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Apellido de la persona', max_length=50, verbose_name='Apellido')),
                ('img_persona', models.ImageField(blank=True, help_text='Imagen de la persona', null=True, upload_to='persona_img', verbose_name='Imagen')),
                ('director', models.BooleanField(default=False, help_text='Identifica si la persona es director', verbose_name='Es Director')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_persona', models.ForeignKey(blank=True, help_text='Actriz o actor que conforman el casting de una pelicula', null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.persona', verbose_name='Actriz o Actor')),
            ],
            options={
                'verbose_name': 'Castgin',
                'verbose_name_plural': 'Castings',
            },
        ),
    ]
