# Generated by Django 3.2 on 2021-05-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_delete_casting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='img_persona',
            field=models.CharField(blank=True, help_text='Imagen de la persona', max_length=500, null=True, verbose_name='Imagen'),
        ),
    ]
