# Generated by Django 3.2 on 2021-05-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_auto_20210519_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='id_imdb',
            field=models.CharField(blank=True, help_text='ID unico de IMDb', max_length=25, null=True, unique=True, verbose_name='ID IMDb'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre_apellido',
            field=models.CharField(help_text='Nombre y Apellido de la persona', max_length=100, verbose_name='Nombre y Apellido'),
        ),
    ]
