# Generated by Django 3.1.7 on 2021-06-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210605_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vista',
            name='review',
            field=models.TextField(default='', help_text='Breve resumen de la pelicula', max_length=500, null=True, verbose_name='Resumen'),
        ),
    ]
