# Generated by Django 3.2 on 2021-05-19 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_casting_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Casting',
        ),
    ]
